### ISSUE TITLE
Possibility of `relax_strict_optional_primitives` for protobuf stub

### ISSUE THREAD

**Issue by miaachan** [nipunn1313/mypy-protobuf#344]
Hi maintainers, 

Right now, protobuf stubs are hosted in typeshed (https://github.com/python/typeshed/tree/master/stubs/protobuf) and all of them are generated to be non-nullable e.g., `BoolValue`, `UInt32Value` in https://github.com/python/typeshed/blob/master/stubs/protobuf/google/protobuf/wrappers_pb2.pyi.

However, as specified in README, proto3 convert None -> zero value internally and one of my projects somehow utilize this property a lot. Is it possible to generate a local copy of protobuf stub with the same effect as `relax_strict_optional_primitives`? This way I can keep the way my code behaves and serve the stub in `MYPYPATH` locally.

**Comment by nipunn1313** [comment]
Ah understood. I would be ok with having the typeshed stubs relax the strict optional primitives for maximum flexibility. I can look into that.
https://github.com/python/typeshed/pull/7038

In the meantime, you can totally do that! Easiest way might be to clone typeshed and patch in the above PR. Then you can add your `/path/to/local/typeshed/stubs/protobuf` to your `MYPYPATH` and it should work.

**Comment by nipunn1313** [comment]
Appreciate the bugreport!

**Comment by nipunn1313** [comment]
types-protobuf 3.19.7 appears to have the fix!
https://pypi.org/project/types-protobuf/

**Comment by miaachan** [comment]
Thanks for the speedy follow-up!
