### ISSUE TITLE
Use official style for generated stubs

### ISSUE THREAD

**Issue by q0w** [nipunn1313/mypy-protobuf#378]
- Style-guide: https://typing.readthedocs.io/en/latest/source/stubs.html
- Test against [flake8-pyi](https://github.com/PyCQA/flake8-pyi) 
- Use the same lint settings like in [python/typeshed](https://github.com/python/typeshed)

e.g.
- `Ellipsis(...)` instead of `pass` for Function body
- str instead of typing.Text (because py2 support was dropped already)
- collections.abc.* instead of typing collections
- remove docstrings

**Comment by nipunn1313** [comment]
(Mostly) Sounds good!

Docstrings are there for a reason - for autocompletion information - since the original _pb2 generated code doesn't generate docstrings - so we'll keep those, but most of these style changes seem reasonable and standardized.

**Comment by nipunn1313** [comment]
Yes - that sounds good in spirit.

I have a preference for generating black/isort conformant stubs and validating them with a testsuite that does `black --check` and `isort --check`. That way black/isort don't become part of the dependencies of mypy-protobuf.

Generating code - and then post-formatting it can make it difficult to understand/debug what the code generator itself is doing, but I think we can achieve the goal without sacrificing this.

**Comment by Evgenus** [comment]
@q0w 

> collections.abc.* instead of typing collections

Where do you see this? I can't find

> remove docstrings

What docstrings? "this code is autogenerated" warnings?

**Comment by q0w** [comment]
@Evgenus check typeshed code and flaks8-pyi rules.
