### ISSUE TITLE
flake8-noqa reports unused `noqa` comments in generated protobuf stubs

### ISSUE THREAD

**Issue by AlexWaygood** [nipunn1313/mypy-protobuf#413]
I recently tried running flake8 on typeshed with the [flake8-noqa](https://github.com/plinss/flake8-noqa) plugin installed, to see if we had any unnecessary `noqa` comments lying around. Among several other hits (some of which were fixed in https://github.com/python/typeshed/pull/8639), flake8-noqa reported the following:

```
stubs\protobuf\google\protobuf\struct_pb2.pyi:55:133: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\type_pb2.pyi:56:127: NQA102 "# noqa: F821" has no matching violations
```

These `noqa` comments do indeed seem to be unnecessary when using the latest version of flake8.

flake8-relevant details of my local environment:

```
flake8==5.0.4
flake8-bugbear==22.7.1
flake8-noqa==1.2.9
flake8-pyi==22.8.1
```

(This doesn't need to be high priority. For several other reasons, I think it's unlikely we'll be able to enable flake8-noqa's `NQA102` in CI at typeshed right now, anyway 🙂)

**Comment by nipunn1313** [comment]
The #noqa was for https://github.com/PyCQA/flake8-pyi/issues/278 - maybe flake8 fixed it? Will poke around when I get some time.

**Comment by AlexWaygood** [comment]
Thanks for the quick response on this @nipunn1313!
