### ISSUE TITLE
Not generating .py files from protouf file using this plugin 

### ISSUE THREAD

**Issue by vishaldhanani** [nipunn1313/mypy-protobuf#474]
Hello,

I have cloned this repo locally and installed all required packages as you have mentioned in your readme. I am trying to generate .py files from protobuf but it's throwing a `Missing input file` error. 

Here is the execution command I'm using while compiling the protobuf file in the windows system. 
```
protoc --python_out=*.proto --mypy_out=.
```
Can you please clarify more in your readme and also give any working example in the readme to replicate the same example?'

Thank you,
Vishal

**Comment by nipunn1313** [comment]
Hello. You need to provide the `.proto` files as inputs on the command line, per the python protobuf tutorial
https://developers.google.com/protocol-buffers/docs/pythontutorial#compiling-your-protocol-buffers

If you have ideas on how to improve the readme to make this more clear, send over a PR and I'm happy to take a look.
