### ISSUE TITLE
timeout should be float

### ISSUE THREAD

**Issue by Dreamsorcerer** [nipunn1313/mypy-protobuf#533]
The GRPC timeout parameter looks like it should be `float`, not `int` (I see several examples online using `0.5`).

**Comment by snuderl** [comment]
I just integrated stubs into our projects, and we have multiple usages of float that work perfectly fine

**Comment by Dreamsorcerer** [comment]
Nevermind, it's in another repo: https://github.com/shabbyrobe/grpc-stubs/pull/45/files

(Maybe you don't have the stubs installed?)
