### ISSUE TITLE
Release version on pypi is to low!

### ISSUE THREAD

**Issue by RuofengX** [nipunn1313/mypy-protobuf#535]
I am using async grpc like `await stub.HelloWorld(Request)`, but I found that there isn't an async stub, then I found again that there actually has a [pull request](https://github.com/nipunn1313/mypy-protobuf/pull/489) to fix this issue. However, the latest pypi package([v3.4.0](https://github.com/nipunn1313/mypy-protobuf/releases/tag/v3.4.0)) didn't contain that pr, moreover the latest version 3.4.0 on pypi is published last year.

So I followed the guide in README to install latest version from github repo, issue fixed. I think it is because author didn't release new version on pypi.

**Comment by nipunn1313** [comment]
thank you for the reminder. I will get to it. I admit it has been a long time.

**Comment by nipunn1313** [comment]
It's complete now! 3.5.0
