### ISSUE TITLE
Ignoring field names equal to reserved keywords like "from"

### ISSUE THREAD

**Issue by devgomax** [nipunn1313/mypy-protobuf#553]
Hello! Here is the proto message for example:
```proto
message Range {
    google.protobuf.FloatValue from = 1;
    google.protobuf.FloatValue to = 2;
}
```
And there is the generated interface:
```python
class Range(Message):
    DESCRIPTOR: Descriptor
    FROM_FIELD_NUMBER: int
    TO_FIELD_NUMBER: int
    @property
    def to(self) -> FloatValue: ...
    def __init__(self,
        *,
        to: Optional[FloatValue] = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["from",b"from","to",b"to"]) -> bool: ...
    def ClearField(self, field_name: Literal["from",b"from","to",b"to"]) -> None: ...
```
Unfortunately, generated model has no field named `from`.
So I have two questions:
1) How can I get/set this field while initialization of the model `Range`?
2) Is there any workaround for such fields?

Thanks in advance!

**Comment by nipunn1313** [comment]
Hi. `from` is a python reserved keyword so it is skipped on the `property`. You will have to use some methods from the base class - the `getattr` and `setattr`

See this for details
https://github.com/protocolbuffers/protobuf/issues/3871
