### ISSUE TITLE
Manage optional field in Message body

### ISSUE THREAD

**Issue by Dufgui** [nipunn1313/mypy-protobuf#579]
Optional field are well manage in constructor but not in the class field declaration. I think it"s a quick fix to do in writeMessage as I can see but not sure. Today generation is:
```
class MyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    field1: builtins.str
    optionalfield1: builtins.str
    optionalfield2: builtins.str
    def __init__(
        self,
        *,
        field1: builtins.str = ...,
        optionalfield1: builtins.str | None = ...,
        optionalfield2: builtins.str | None = ...,
    ) -> None: ...
```
But it must be:
```
class MyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    field1: builtins.str
    optionalfield1: builtins.str | None
    optionalfield2: builtins.str | None
    def __init__(
        self,
        *,
        field1: builtins.str = ...,
        optionalfield1: builtins.str | None = ...,
        optionalfield2: builtins.str | None = ...,
    ) -> None: ...
```

**Comment by nipunn1313** [comment]
my understanding is that for proto3, scalar non-repeated fields are not actually optional on the wire, nor on the generated class. IE - if you construct it with None, my understanding is that you will get the 0-value.

https://github.com/nipunn1313/mypy-protobuf/blob/7506de3f39469e1a6665f1bf388f506a40571996/mypy_protobuf/main.py#L439

It's possible my understanding is wrong. I'd be welcome to a fix - as long as it includes a unit test that proves that this behavior is expected - eg https://github.com/nipunn1313/mypy-protobuf/blob/7506de3f39469e1a6665f1bf388f506a40571996/test/test_generated_mypy.py#L421

**Comment by RonaldGalea** [comment]
With the newest version of protobuf, it seems that it's possible to explicitly mark scalar fields as `optional` and therefore track set/not set information (see [this SO post](https://stackoverflow.com/a/62566052/11820733)). This would allow generating the optional types, right?

**Comment by nipunn1313** [comment]
I made an error in my previous message

> ~my understanding is that for proto3, scalar non-repeated fields are not actually optional on the wire, nor on the generated class. IE -~ if you construct it with None, my understanding is that you will get the 0-value.

Actually, the fields are optional on the wire, however if you access them in the generated class, you will still get the 0-value. The behavior is documented here.

https://protobuf.dev/reference/python/python-generated/#singular-fields-proto3
<img width="943" alt="image" src="https://github.com/user-attachments/assets/811c3b4a-b24d-42c7-81bd-28abf0d82e27">

I was able to validate this with an improvement to the unit test in #655. You can check it out to prove the behavior returns the 0-value rather than `None` on field access.
