### ISSUE TITLE
Where is the tag for version 3.6.0?

### ISSUE THREAD

**Issue by kojiromike** [nipunn1313/mypy-protobuf#605]
In debugging an issue (python/typeshed#11636 in fact), I saw in the dist-info/METADATA that the version of types_protobuf I'm using (`Version: 5.26.0.20240422`) was `Generated using [mypy-protobuf==3.6.0](https://github.com/nipunn1313/mypy-protobuf/tree/v3.6.0) and libprotoc 25.1 on [protobuf v26.1](https://github.com/protocolbuffers/protobuf/releases/tag/v26.1) (python protobuf==5.26.1)`.

While 3.6.0 [does exist on pypi.org](https://pypi.org/project/mypy-protobuf/3.6.0/), there does not appear to be such a tag in this repo on github, and indeed the link provided in the METADATA file is broken. Is it an oversight?

Thanks for all your hard work.

**Comment by nipunn1313** [comment]
mistake! Thank you for pointing it out. Just fixed.
