### ISSUE TITLE
Upstream plugin into protoc

### ISSUE THREAD

**Issue by henribru** [nipunn1313/mypy-protobuf#95]
Is there a possibility of upstreaming this and including it in `protoc`'s Python plugin? I don't know how difficult it would be to integrate, but the protobuf team is at least accepting contributions to generate type hints: https://github.com/protocolbuffers/protobuf/issues/2638#issuecomment-495003625

**Comment by nipunn1313** [comment]
sounds like a great idea. I think having separate generated .pyi files is better than trying to inline into the `.py` files because the autogenerated code is pretty gnarly - but having them ship together totally makes sense.

**Comment by nipunn1313** [comment]
would be open to contributions in the area! It might be possible to have the protobuf library depend on mypy-protobuf, and internally use both plugins - to generate both `.py` and `.pyi`

**Comment by artificial-aidan** [comment]
With the release of pyi stub generation in protoc (https://github.com/protocolbuffers/protobuf/issues/2638#issuecomment-1034471949) do you still plan to maintain this module?

**Comment by nipunn1313** [comment]
Yep! Will continue to maintain as mypy-protobuf has been the de facto standard for many years

Though I don’t expect to upstream it any more, so I’ll close this.

I’ll try to add a comment to the readme with a technical plan
